config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from rest_framework import routers
from django.conf.urls.static import static
from product.views import *

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'cart', CartViewSet)

urlpatterns = [
    path('', include('product.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [ 
    # ================================ PRODUCT ================================
    path('', views.ProductListView.as_view(), name='product_list'),
    path('product/new/', views.ProductCreateView.as_view(), name='product_new'),
    path('product/detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    
    # ================================ CART ================================
    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/new/', views.CartCreateView.as_view(), name='cart_new'),
    path('cart/detail/<int:pk>/', views.CartDetailView.as_view(), name='cart_detail'),
    path('cart/update/<int:pk>/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/delete/<int:pk>/', views.CartDeleteView.as_view(), name='cart_delete'),
    
    path('cart/finalize_purchase/', views.finalize_purchase, name='finalize_purchase'),
]

product/models.py
from django.core.exceptions import ValidationError
from django.urls import reverse 
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    minimum = models.IntegerField(default=1)
    amount_per_package = models.IntegerField(default=0)
    max_availability = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product:product_list")

class Cart(models.Model):
    product_id = models.ForeignKey(Product, verbose_name="Product", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return self.product_id.name

    def get_absolute_url(self):
        return reverse("product:cart_list")
 
    def price(self):
        return self.product_id.price

    def subtotal(self):
        return self.quantity * self.product_id.price

    def minimum(self):
        return self.product_id.minimum
    
    def amount_per_package(self):
        return self.product_id.amount_per_package
    
    def save(self, *args, **kwargs):
        if self.id:
            self.validations()
            return super(Cart, self).save(*args, **kwargs)
        else:
            exist_product = Cart.objects.filter(product_id=self.product_id.id)
            
            if exist_product:
                for p in exist_product:
                    p.quantity += self.quantity
                    p.validations()
                    p.save()
            else:
                self.validations()
                super(Cart, self).save(*args, **kwargs)

    def validations(self):
        if self.quantity < self.product_id.minimum:
            raise ValidationError(f"Minimum valid quantity: {self.product_id.minimum}")

        if self.quantity % self.product_id.amount_per_package:
            raise ValidationError(f"Selected quantity is not compatible with the quantity per package {self.product_id.amount_per_package} of product {self.product_id}")
        
        if self.quantity > self.product_id.max_availability:
            raise ValidationError(f"Quantity greater than available: {self.product_id.max_availability}")

product/views.py
import sys
from product.models import *
from product.serialize import *
from django.shortcuts import get_object_or_404, render
from rest_framework import viewsets
from django.views.generic import *
from product.form import *

""" ==============================================
                    Viewsets
==============================================="""

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer


""" ==============================================
                    Product
==============================================="""

class ProductListView(ListView):
    context_object_name = 'products'
    template_name = 'product/product_list.html'
    queryset = Product.objects.all

    def get_queryset(self):
        filter_prod = self.request.GET.get("product")
        if filter_prod:
            products = Product.objects.filter(name__icontains=filter_prod)
        else:
            products = Product.objects.all

        return products

class ProductDetailView(DetailView):
    template_name = 'product/product_detail.html'

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs.get('pk'))

class ProductCreateView(CreateView):
    form_class = ProductModelForm
    template_name = 'product/product_create.html'
    queryset = Product.objects.all() 

class ProductUpdateView(UpdateView): 
    form_class = ProductModelForm
    template_name = 'product/product_create.html'

    def get_queryset(self):
        return Product.objects.filter(pk=self.kwargs.get('pk'))

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/product_confirm_delete.html'
    success_url = "/"


""" ==============================================
                    Cart
==============================================="""

class CartListView(ListView):
    context_object_name = "cart"
    template_name = 'cart/cart_list.html'
    queryset = Cart.objects.all()

class CartDetailView(DetailView):
    template_name = 'cart/cart_detail.html'

    def get_object(self):
        return get_object_or_404(Cart, id=self.kwargs.get('pk'))

class CartCreateView(CreateView): 
    form_class = CartModelForm
    template_name = 'cart/cart_create.html'
    queryset = Cart.objects.all()

class CartUpdateView(UpdateView): 
    form_class = CartModelForm
    template_name = 'cart/cart_create.html'

    def get_queryset(self):
        return Cart.objects.filter(pk=self.kwargs.get('pk'))

class CartDeleteView(DeleteView):
    model = Cart
    template_name = 'cart/cart_confirm_delete.html'
    success_url = "/cart"

def finalize_purchase(request):
    Cart.objects.all().delete()
    return render(request, 'cart/cart_list.html')

def handler500(request, *args, **argv):
    traceback = sys.exc_info()[1]
    try:
        context = {'error': list(traceback)[0]}
    except:
        context = {'error': traceback}

    return render(request, "errors/500.html", context)

product/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/django.ico' %}"
    />
    <title>{% block title%}{% endblock %}</title>
  </head>
  <body>
    <div class="container_main">
      {% include 'base/menu.html'%} 
      {% block other_content %}{% endblock %}
      <div class="container-table100">
        <div class="wrap-table100">
          <div class="table100">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </body>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
    crossorigin="anonymous"
  />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"
  ></script>
  <link
    href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
    rel="stylesheet"
    id="bootstrap-css"
  />
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>

product/templates/base/menu.html
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'product:product_list' %}">
          <i class="fa fa-book"></i>
          Products
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'product:cart_list' %}">
          <i class="fa fa-shopping-cart"></i>
          Cart
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/api/">
          <i class="fa fa-database"></i>
          List API
        </a>
      </li>
    </ul>
  </div>
</nav>

product/templates/cart/cart_confirm_delete.html
{% extends 'base/base.html' %} 

{% block title %}Delete Cart{% endblock %} 

{%block content %}
<h2 class="form_name">Delete product from cart</h2>

<div class="container">
  <div class="box">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete product {{ object }} from the cart?</p>
      <button type="submit" class="btn btn-danger">
        <a>Confirm</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:cart_list' %}">Cancel</a>
      </button>
    </form>
  </div>
</div>
{% endblock %}

product/templates/cart/cart_create.html
{% extends 'base/base.html' %} 

{% block title %}Cart{% endblock %} 

{% block content %}

<h2 class="form_name">Insert/Update Product in the cart</h2>
<div class="container">
  <div class="box">
    <form action="." method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" class="btn btn-success">
        <a>Send</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:cart_list' %}">Cancel</a>
      </button>
    </form>
  </div>
</div>
{% endblock %}

product/templates/cart/cart_detail.html
{% extends 'base/base.html' %} 

{% block title %}Cart Detail{% endblock %} 

{%block content %}
<h2 class="form_name">Detail Product</h2>

<div class="container">
  <div class="box">
    <form action="." method="get" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
        <label for="product_id">
          Product:
          <input
            type="text"
            id="product_id"
            value="{{ object.product_id }}"
            disabled
          />
        </label>
      </p>
      <p>
        <label for="quantity ">
          Quantity:
          <input
            type="text"
            id="quantity "
            value="{{ object.quantity  }}"
            disabled
          />
        </label>
      </p>
      <button class="btn btn-warning">
        <a href="{% url 'product:cart_update' object.pk %}">Edit</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:cart_list' %}">Return</a>
      </button>
    </form>
  </div>
</div>
{% endblock %}

product/templates/cart/cart_list.html
{% extends 'base/base.html' %} 

{% block title %}Shopping Cart{% endblock %} 

{%block content %}

<h1>Shopping Cart (<a href="/api/cart" class="btn btn-light">API</a>)</h1>
<hr />

<a href="{% url 'product:cart_new' %}">
  <button class="btn btn-success">Add Product</button>
</a>

<table style="margin-top: 20px">
  <thead>
    <tr class="table100-head">
      <th class="column1">Product</th>
      <th class="column3">Minimum</th>
      <th class="column5">Amount Per Package</th>
      <th class="column2">Price</th>
      <th class="column4">Quantity</th>
      <th class="column6">Subtotal</th>
      <th class="column7">Options</th>
    </tr>
  </thead>
  <tbody>
    {% for product in cart %}
    <tr>
      <td class="column1" title="{{product.product_id}}">
        {{product.product_id}}
      </td>
      <td class="column3" title="{{product.minimum}}">{{product.minimum}}</td>
      <td class="column5" title="{{product.amount_per_package}}">
        {{product.amount_per_package}}
      </td>
      <td class="column2" title="{{product.price}}">R$ {{product.price}}</td>
      <td class="column4" title="{{product.quantity}}">{{product.quantity}}</td>
      <td class="column6" title="{{product.subtotal}}">
        R$ {{product.subtotal}}
      </td>
      <td class="column7">
        <a
          href="{% url 'product:cart_detail' product.pk %}"
          style="color: #e0bf00"
        >
          <i
            class="fa fa-refresh"
            style="padding-right: 15px"
            title="Update"
          ></i>
        </a>
        <a
          href="{% url 'product:cart_delete' product.pk %}"
          style="color: #e00000"
        >
          <i class="fa fa-trash" title="Delete"></i>
        </a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="6" style="font-size: 18px">
        There are no registered products.
      </td>
    </tr>
    {% endfor%}
    <tr></tr>
  </tbody>
</table>

<div style="float: right; margin: 20px">
  <h1 style="color: #fff">TOTAL: R$ <span id="total"></span></h1>
  <button
    class="btn btn-info"
    style="float: right; width: 300px; height: 50px"
    onclick="start_finalize_purchase()"
  >
    Finalize Purchase
  </button>
</div>

<script>

  var form_finalize_purchase = document.getElementById("form_finalize_purchase");
  var cart_total = document.getElementById("total");
  var total = 0;
  var form_total = document.getElementById("total_form");
  var hashcode = "";

  function finalize_purchase() {
    for (var i = 0; i < 4; i++){
      hashcode += geraNumeroUnico()
      if (i != 3){
        hashcode += "-"
      }
    }

    alert(
      "Purchase completed successfully \n\n" +
        "ID Purchase: " +
        hashcode +
        "\nTotal Price: R$" +
        cart_total.innerHTML
    );
  }

  function geraNumeroUnico() {
    return Math.round(Math.random() * 1e8) + 1000;
  } 

  function start_finalize_purchase() {
    if (cart_total.innerHTML == 0) {
      alert("Select a product to complete the purchase");
    } else {
      form_total.value = cart_total.innerHTML;
      form_finalize_purchase.style.display = "flex";
    }
  }
  function close_form_finalize_purchase() {
    form_finalize_purchase.style.visibility =
      "hidden";
  }
  async function calculate_total() {
      let response = await fetch("/api/cart/");
      let data = await response.json();
      
      if (!data.length){
        cart_total.innerHTML = 0;
      }
      else{
        for (i in data) {
            search_product(data[i]["product_id"], data[i]["quantity"])
        }
      }
  }
  
  async function search_product(id, quantity) {
      let response = await fetch("/api/products/"+ id);
      let data = await response.json();
      total += data["price"] * quantity
  
      cart_total.innerHTML = total;
  }
  calculate_total()
</script>

{% endblock %} 

{% block other_content %} 
  {% include 'cart/finalize_purchase.html' %} 
{% endblock %}

product/templates/cart/finalize_purchase.html
<div id="form_finalize_purchase" class="container form_finalize">
  <div class="box">
    <form action="." enctype="multipart/form-data">
      {% csrf_token %}
      <p>
        <h3 style="text-align: center">Finalize Purchase</h1>
      </p>
      <p>
        <label for="payment_method">
          Payment Method:
          <select name="payment_method" style="padding-right: 60px;">
            <option value="debit" selected>Debit</option>
            <option value="credit">Credit</option>
            <option value="cash">Cash</option>
          </select>
        </label>
      </p>
      <div>
        <div>
          <p>
            <label for="total_input">
              TOTAL: R$ <input type="text" name="total_input" id="total_form" disabled style="width: 200px;">
            </label>
          </p>
        </div>
        <button class="btn btn-success" onclick="finalize_purchase()">
          <a href="{% url 'product:finalize_purchase' %}" style="color: white">Confirm</a>
        </button>
        <button class="btn btn-light" style="border-color: rgb(157, 157, 157)"  onclick="close_form_finalize_purchase()">
          Cancel
        </button>

      </div>
    </form>
  </div>
</div>

product/templates/product/product_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %}Delete Products{% endblock %}

{% block content %}
<h2 class="form_name">Delete product</h2>

<div class="container">
  <div class="box">
    <form method="post">
      {% csrf_token %}
      <p>
        Are you sure you want to delete product {{ object }}?
      </p>
      <button type="submit" class="btn btn-danger">
        <a>Confirm</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:product_list' %}">Cancel</a>
      </button>
    </form>
  </div>
</div>
{% endblock %}
   

product/templates/product/product_create.html
{% extends 'base/base.html' %} 

{% block title %}Product{% endblock %} 

{% block content %}
<h2 class="form_name">Create/Update Product</h2>
<div class="container">
  <div class="box">
    <form action="." method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" class="btn btn-success">
        <a>Send</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:product_list' %}">Cancel</a>
      </button>
    </form>
  </div>
</div>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'base/base.html' %} 

{% block title %}Products Detail{% endblock %} 

{%block content %}
<h2 class="form_name">Detail Product</h2>

<div class="container">
  <div class="box">
    <form action="." method="get" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
        <label for="name">
          Product:
          <input type="text" id="name" value="{{ object.name }}" disabled />
        </label>
      </p>
      <p>
        <label for="price ">
          Price:
          <input type="text" id="price " value="{{ object.price  }}" disabled />
        </label>
      </p>
      <p>
        <label for="minimum ">
          Minimum:
          <input
            type="text"
            id="minimum "
            value="{{ object.minimum  }}"
            disabled
          />
        </label>
      </p>
      <p>
        <label for="amount_per_package ">
          Amount per package:
          <input
            type="text"
            id="amount_per_package "
            value="{{ object.amount_per_package  }}"
            disabled
          />
        </label>
      </p>
      <p>
        <label for="max_availability ">
          Max availability:
          <input
            type="text"
            id="max_availability "
            value="{{ object.max_availability  }}"
            disabled
          />
        </label>
      </p>
      <button class="btn btn-warning">
        <a href="{% url 'product:product_update' object.pk %}">Edit</a>
      </button>
      <button class="btn btn-light">
        <a href="{% url 'product:product_list' %}">Return</a>
      </button>
    </form>
  </div>
</div>

{% endblock %}

product/templates/product/product_list.html
{% extends 'base/base.html' %} 

{% block title %}Products{% endblock %} 

{% block content %}

<h1>
  List Of Products (<a href="/api/products" class="btn btn-light">API</a>)
</h1>
<hr />

<a href="{% url 'product:product_new' %}">
  <button class="btn btn-success">Create</button>
</a>

<form action="?" method="GET" style="margin-bottom: 20px; float: right">
  <label for="product" style="color: #fff; font-size: 19px">Search: </label>
  <input
    type="text"
    name="product"
    value="{{ request.GET.product }}"
    class="p1 border"
    autocomplete="off"
    placeholder="Product Name"
    style="border-radius: 5px; padding: 3px"
  />
  <button type="submit" class="btn btn-success">Find</button>
  <a href="{% url 'product:product_list' %}" class="btn btn-light">Clear</a>
</form>

<table>
  <thead>
    <tr class="table100-head">
      <th class="column1">ID</th>
      <th class="column2">Name</th>
      <th class="column3">Price</th>
      <th class="column4">Minimum</th>
      <th class="column5">Amount Per Package</th>
      <th class="column6">Max Availability</th>
      <th class="column7">Options</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <td class="column1" id="product_id_{{product.id}}">{{product.id}}</td>
      <td class="column2">{{product.name}}</td>
      <td class="column3">R$ {{product.price}}</td>
      <td class="column4">{{product.minimum}}</td>
      <td class="column5">{{product.amount_per_package}}</td>
      <td class="column6">{{product.max_availability}}</td>
      <td class="column7">
        <a
        href="{% url 'product:cart_list' %}"
        style="color: #e0bf00"
        >
        <i
          class="fa fa-cart-plus"
          style="padding-right: 15px; color: #007AA5"
          title="Add to Cart"
        ></i>
        </a>
        <a
          href="{% url 'product:product_detail' product.pk %}"
          style="color: #e0bf00"
        >
          <i
            class="fa fa-refresh"
            style="padding-right: 15px"
            title="Update"
          ></i>
        </a>
        <a
          href="{% url 'product:product_delete' product.pk %}"
          style="color: #e00000"
        >
          <i class="fa fa-trash" title="Delete"></i>
        </a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="6">There are no registered products.</td>
    </tr>
    {% endfor%}
    <tr></tr>
  </tbody>
</table>
{% endblock %}